language: node_js
node_js:
  - 9
  - 8
  - 6
cache:
  directories:
    - $HOME/.npm
before_install:
  - npm install --global npm@5.6.0
  - npm --version
install: npm install --no-shrinkwrap --prefer-online
