build: off
cache:
  - '%APPDATA%\npm-cache'
clone_depth: 1
skip_branch_with_pr: true
skip_commits:
  files:
    - '**/*.md'
environment:
  TSD_GITHUB_TOKEN:
    secure: M2aeRAmpcwy5eOC0ODWCWIk+st2GTsMlHzArP5/gEPJOylFkNV95sHo2Z4mfcd0h
  GITHUB_OAUTH_TOKEN:
    secure: M2aeRAmpcwy5eOC0ODWCWIk+st2GTsMlHzArP5/gEPJOylFkNV95sHo2Z4mfcd0h
  matrix:
    - nodejs_version: 9
      platform: x64
    - nodejs_version: 9
      platform: x86
    - nodejs_version: 8
    - nodejs_version: 6
matrix:
  fast_finish: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install --global npm@5.6.0
  - npm --version
  - git config core.symlinks true
  - git reset --hard
  - npm install --no-shrinkwrap --prefer-online
test_script:
  - npm test
