environment:
  TSD_GITHUB_TOKEN:
    secure: M2aeRAmpcwy5eOC0ODWCWIk+st2GTsMlHzArP5/gEPJOylFkNV95sHo2Z4mfcd0h
  GITHUB_OAUTH_TOKEN:
    secure: M2aeRAmpcwy5eOC0ODWCWIk+st2GTsMlHzArP5/gEPJOylFkNV95sHo2Z4mfcd0h
  matrix:
    - nodejs_version: 12
    - nodejs_version: 10
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
test_script:
  - npm test
